esphome:
  name: esphome_web_ir
  friendly_name: IR Receiver
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: arduino


# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "redacted"

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: 'WPA2'

remote_receiver:
  pin:
    number: GPIO32
    inverted: true
    mode:
      input: true
      pullup: true
  dump: all

binary_sensor:
#  - platform: gpio
#    name: "Gas detected"
#    pin:
#      number: GPIO27
#      mode: INPUT_PULLUP
#      inverted: true
#    device_class: gas
#    filters:
#      - delayed_on: 5s
#      - delayed_off: 10s

  - platform: remote_receiver
    name: "IR Taste 1"
    nec:
      address: 0xEF00
      command: 0xFF00
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_1

  - platform: remote_receiver
    name: "IR Taste 2"
    nec:
      address: 0xEF00
      command: 0xFE01
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_2

  - platform: remote_receiver
    name: "IR Taste 3"
    nec:
      address: 0xEF00
      command: 0xFD02
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_3

  - platform: remote_receiver
    name: "IR Taste 4"
    nec:
      address: 0xEF00
      command: 0xFC03
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_4

  - platform: remote_receiver
    name: "IR Taste 5"
    nec:
      address: 0xEF00
      command: 0xFB04
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_5

  - platform: remote_receiver
    name: "IR Taste 6"
    nec:
      address: 0xEF00
      command: 0xFA05
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_6

  - platform: remote_receiver
    name: "IR Taste 7"
    nec:
      address: 0xEF00
      command: 0xF906
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_7

  - platform: remote_receiver
    name: "IR Taste 8"
    nec:
      address: 0xEF00
      command: 0xF807
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_8

  - platform: remote_receiver
    name: "IR Taste 9"
    nec:
      address: 0xEF00
      command: 0xF708
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_9

  - platform: remote_receiver
    name: "IR Taste 10"
    nec:
      address: 0xEF00
      command: 0xF609
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_10

  - platform: remote_receiver
    name: "IR Taste 11"
    nec:
      address: 0xEF00
      command: 0xF50A
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_11

  - platform: remote_receiver
    name: "IR Taste 12"
    nec:
      address: 0xEF00
      command: 0xF40B
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_12

  - platform: remote_receiver
    name: "IR Taste 13"
    nec:
      address: 0xEF00
      command: 0xF30C
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_13

  - platform: remote_receiver
    name: "IR Taste 14"
    nec:
      address: 0xEF00
      command: 0xF20D
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_14

  - platform: remote_receiver
    name: "IR Taste 15"
    nec:
      address: 0xEF00
      command: 0xF10E
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_15

  - platform: remote_receiver
    name: "IR Taste 16"
    nec:
      address: 0xEF00
      command: 0xF00F
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_16

  - platform: remote_receiver
    name: "IR Taste 17"
    nec:
      address: 0xEF00
      command: 0xEF10
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_17

  - platform: remote_receiver
    name: "IR Taste 18"
    nec:
      address: 0xEF00
      command: 0xEE11
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_18

  - platform: remote_receiver
    name: "IR Taste 19"
    nec:
      address: 0xEF00
      command: 0xED12
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_19

  - platform: remote_receiver
    name: "IR Taste 20"
    nec:
      address: 0xEF00
      command: 0xEC13
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.ir_taste_20
